name: 'TWIN Node 101'

services:
  db:
    image: mysql:8.4.7
    container_name: mysql8_container
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: twin
      MYSQL_PASSWORD: twin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  twin-node-bootstrap:
    image: twinfoundation/twin-node:0.0.3-next.20
    depends_on:
      - db
    env_file: ./.env
    volumes: 
      - twin_data:/var/lib/twin
      - ./.env.bootstrap:/app/.env.bootstrap
    command: |
      sh -c 'node src/index.js bootstrap-legacy --load-env=.env.bootstrap'


  twin-node:
    image: twinfoundation/twin-node:0.0.3-next.20
    container_name: twin_node
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file: ./.env
    volumes: 
      - twin_data:/var/lib/twin


volumes:
  mysql_data:
  twin_data:
