name: 'TWIN Node 101'

services:
  db:
    image: mysql:8.4.7
    container_name: mysql8_container_
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: twin
      MYSQL_PASSWORD: twin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  twin-node-bootstrap:
    image: twinfoundation/twin-node:0.0.3-next.46
    depends_on:
      - db
    env_file: ../../common/.env
    volumes: 
      - twin_data:/var/lib/twin
      - ../../common/.env.bootstrap-legacy:/app/.env.bootstrap-legacy
    command: |
      sh -c 'node src/index.js bootstrap-legacy --load-env=.env.bootstrap-legacy'


  twin-node:
    image: twinfoundation/twin-node:0.0.3-next.46
    container_name: twin_node_
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file: ../../common/.env
    volumes: 
      - twin_data:/var/lib/twin


volumes:
  mysql_data:
  twin_data:
